### ISSUE TITLE
NY Times data lags JHU data

### ISSUE THREAD

**Issue by gregf83** [coviddata/coviddata#10]
It seems NY Times is a day or two behind JHU. 

One option to maintain up to date State level date would be to freeze the time series state data as is and append data for each new day from the 'live' JHU data (updated hourly).

**Comment by bfosten** [comment]
Good idea! I've implemented this in f1b0298ab6ab324e9ba0c97deb5ef4187433cf59, and the data has been updated using this new strategy.
