### ISSUE TITLE
Data not updating any longer?

### ISSUE THREAD

**Issue by jum** [coviddata/coviddata#21]
I am seeing that several days now there has been no new data arriving. Anything that can be done about that?

**Comment by smartcuc** [comment]
Well, seeing the same. No updates any more.... :-(

**Comment by Crabbey** [comment]
Looks like the task is failing to parse one of the incoming CSV files in the automated action tasks:
CSV Headers: FIPS, Admin2, Province_State, Country_Region, Last_Update, Lat, Long_, Confirmed, Deaths, Recovered, Active, Combined_Key, Incidence_Rate, Case-Fatality_Ratio
/home/runner/work/coviddata/coviddata/src/sources/jhu_csse/standardize.rb:47:in `row_to_location_names': Missing country (RuntimeError)
	from /home/runner/work/coviddata/coviddata/src/sources/jhu_csse/standardize.rb:33:in `add_output_row'
	from /home/runner/work/coviddata/coviddata/src/sources/jhu_csse/standardize.rb:27:in `block (2 levels) in standardize_data'
	from /opt/hostedtoolcache/Ruby/2.6.6/x64/lib/ruby/2.6.0/csv/table.rb:337:in `each'

I'm not overly confident with Ruby, so I'm not sure of the best way to address this.

**Comment by jum** [comment]
Today the data is back! Thanks whoever fixed it.

**Comment by jum** [comment]
Well, it has not been updating for a few days again.

**Comment by jum** [comment]
Ok, it is flowing again.
