### ISSUE TITLE
docs: methodology

### ISSUE THREAD

**Issue by Akuukis** [coviddata/coviddata#3]
Great stuff! I wish I could use it for my dashboard [Pandemic Estimator](https://pandemic-estimator.net/) but for that your API lacks documentation on methodology. I'm using JHU directly and I know what chaos it is, the most blatant example being that they provide "cumulative data" that's not cumulative quite often in practice. And the whole change of file formats, etc.

Can you please describe methodology how you deal with it? What has been omitted, what has been "adjusted" and how? Thank you!

**Comment by bfosten** [comment]
Sure, I've added a [Methodology](https://github.com/coviddata/covid-api#methodology) section in the README that describes the project's methodology.

We've tried to keep the logic relatively simple; if you'd like to take a look at it in more detail, it's all in the [src directory](https://github.com/coviddata/covid-api/tree/master/src).

**Comment by Akuukis** [comment]
FYI what I figured out is that everyone converges to either of 2 popular repositories:
-    coronadatascraper.com does aggregation across loads of sources, both JHU and many national ones
-    https://github.com/ExpDev07/coronavirus-tracker-api are pragmatic about sources and uses only JHU and CSBS
