### ISSUE TITLE
United Kingdom splitted

### ISSUE THREAD

**Issue by neapolis79** [coviddata/coviddata#7]
i was lookng in the countries stats api https://coviddata.github.io/covid-api/v1/countries/stats.json and i found that the united kingom is splitted in two countries one with "uk" key, and another with "united-kingdom"  
the same for Saint Martin with key "saint-martin" and "st-martin"

**Comment by bfosten** [comment]
I've fixed this in 9b92f5d9a71946cacfbd80e4e3ac90320ab68fd0. If other duplicates are found, we can resolve them in [src/config/normalized_location_names.yaml](https://github.com/coviddata/covid-api/blob/master/src/config/normalized_location_names.yaml).
